### ISSUE TITLE
SideMenuItem currently only uses add icon

### ISSUE THREAD

**Issue by PaxPax** [Wolfr/sveltekit-jui#55]
Currently the library is always using the add icon as seen here.

![image](https://user-images.githubusercontent.com/25893271/114312344-f5e43b00-9ab7-11eb-8bac-1863965046b2.png)
We should be using the the icon supplied by the user; also add .8rem style spacing to let the icon breath. Possible solution could look like.
![image](https://user-images.githubusercontent.com/25893271/114312566-a6ead580-9ab8-11eb-8b8e-a7d23572f0ce.png)

I have a fix available, but wondering should the icon and spacing be two separate issues?

**Comment by Wolfr** [comment]
Logged something similar in #54 .

The whole project is in early phase so any improvement is welcome, just PR and I will take a look!

**Comment by PaxPax** [comment]
It would be helpful to have a contribute guideline as well!

**Comment by Wolfr** [comment]
Fixed it.
