### ISSUE TITLE
Bug: when you hit escape to close a nav menu, both of them close or open up

### ISSUE THREAD

**Issue by Wolfr** [Wolfr/sveltekit-jui#61]
![image](https://user-images.githubusercontent.com/12690/114599978-1832b000-9c94-11eb-9a8f-0a017ccf08b1.png)

The global shortcut triggers both nav menus.

Solution: not sure? Give them unique ids, close them through popper? Destroy the element properly? I am not sure, this is not my expertise.

**Comment by stephane-vanraes** [comment]
I had a quick look at the code and it seems that your code is setup to _toggle_ the menu on hitting `Escape` ?

This would mean you can also open them using this key, which is counter intuitive, normally you would have a single key combo (like alt-m or so) to open a menu and have `escape` to close open menus.

If you only need to be able to close them, just change the lines here:
```js
  function handleKeydown(e) {
    if (e.key == trigger) {
      showMenu = !showMenu;
    }
  }
```

to always close the menu: `showMenu = false`

**Comment by Wolfr** [comment]
Right... I was just being inattentive, escape should set to false instead of toggling, totally correct 🤦 ! I need some sleep I think :)
